# Generated by Django 2.1.1 on 2018-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Function', '0002_auto_20180924_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='functions',
        ),
        migrations.AddField(
            model_name='tag',
            name='functions',
            field=models.ManyToManyField(to='Function.Function'),
        ),
    ]
